



spring.datasource.username= ${DB_USER_NAME}
spring.datasource.password= ${DB_PASSWORD}
spring.datasource.url= ${DATA_SOURCE_URL}
spring.datasource.driver-class-name= com.mysql.jdbc.Driver
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true;